/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutMainLayoutImport } from './routes/_layout/_main-layout'
import { Route as LayoutAuthLayoutImport } from './routes/_layout/_auth-layout'
import { Route as LayoutMainLayoutIndexImport } from './routes/_layout/_main-layout/index'
import { Route as LayoutMainLayoutAuthImport } from './routes/_layout/_main-layout/_auth'
import { Route as LayoutMainLayoutEventEventIDImport } from './routes/_layout/_main-layout/event/$eventID'
import { Route as LayoutMainLayoutuserProfileImport } from './routes/_layout/_main-layout/(user)/profile'
import { Route as LayoutAuthLayoutAuthLoginImport } from './routes/_layout/_auth-layout/auth/login'
import { Route as LayoutMainLayoutAuthordersMyOrdersImport } from './routes/_layout/_main-layout/_auth/(orders)/my-orders'
import { Route as LayoutMainLayoutordersOrderCodeImport } from './routes/_layout/_main-layout/(orders)/order.$code'

// Create/Update Routes

const LayoutMainLayoutRoute = LayoutMainLayoutImport.update({
  id: '/_layout/_main-layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutAuthLayoutRoute = LayoutAuthLayoutImport.update({
  id: '/_layout/_auth-layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutMainLayoutIndexRoute = LayoutMainLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutMainLayoutRoute,
} as any)

const LayoutMainLayoutAuthRoute = LayoutMainLayoutAuthImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutMainLayoutRoute,
} as any)

const LayoutMainLayoutEventEventIDRoute =
  LayoutMainLayoutEventEventIDImport.update({
    id: '/event/$eventID',
    path: '/event/$eventID',
    getParentRoute: () => LayoutMainLayoutRoute,
  } as any)

const LayoutMainLayoutuserProfileRoute =
  LayoutMainLayoutuserProfileImport.update({
    id: '/(user)/profile',
    path: '/profile',
    getParentRoute: () => LayoutMainLayoutRoute,
  } as any)

const LayoutAuthLayoutAuthLoginRoute = LayoutAuthLayoutAuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => LayoutAuthLayoutRoute,
} as any)

const LayoutMainLayoutAuthordersMyOrdersRoute =
  LayoutMainLayoutAuthordersMyOrdersImport.update({
    id: '/(orders)/my-orders',
    path: '/my-orders',
    getParentRoute: () => LayoutMainLayoutAuthRoute,
  } as any)

const LayoutMainLayoutordersOrderCodeRoute =
  LayoutMainLayoutordersOrderCodeImport.update({
    id: '/(orders)/order/$code',
    path: '/order/$code',
    getParentRoute: () => LayoutMainLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout/_auth-layout': {
      id: '/_layout/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_main-layout': {
      id: '/_layout/_main-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutMainLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_main-layout/_auth': {
      id: '/_layout/_main-layout/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutMainLayoutAuthImport
      parentRoute: typeof LayoutMainLayoutImport
    }
    '/_layout/_main-layout/': {
      id: '/_layout/_main-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutMainLayoutIndexImport
      parentRoute: typeof LayoutMainLayoutImport
    }
    '/_layout/_auth-layout/auth/login': {
      id: '/_layout/_auth-layout/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof LayoutAuthLayoutAuthLoginImport
      parentRoute: typeof LayoutAuthLayoutImport
    }
    '/_layout/_main-layout/(user)/profile': {
      id: '/_layout/_main-layout/(user)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutMainLayoutuserProfileImport
      parentRoute: typeof LayoutMainLayoutImport
    }
    '/_layout/_main-layout/event/$eventID': {
      id: '/_layout/_main-layout/event/$eventID'
      path: '/event/$eventID'
      fullPath: '/event/$eventID'
      preLoaderRoute: typeof LayoutMainLayoutEventEventIDImport
      parentRoute: typeof LayoutMainLayoutImport
    }
    '/_layout/_main-layout/(orders)/order/$code': {
      id: '/_layout/_main-layout/(orders)/order/$code'
      path: '/order/$code'
      fullPath: '/order/$code'
      preLoaderRoute: typeof LayoutMainLayoutordersOrderCodeImport
      parentRoute: typeof LayoutMainLayoutImport
    }
    '/_layout/_main-layout/_auth/(orders)/my-orders': {
      id: '/_layout/_main-layout/_auth/(orders)/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof LayoutMainLayoutAuthordersMyOrdersImport
      parentRoute: typeof LayoutMainLayoutAuthImport
    }
  }
}

// Create and export the route tree

interface LayoutAuthLayoutRouteChildren {
  LayoutAuthLayoutAuthLoginRoute: typeof LayoutAuthLayoutAuthLoginRoute
}

const LayoutAuthLayoutRouteChildren: LayoutAuthLayoutRouteChildren = {
  LayoutAuthLayoutAuthLoginRoute: LayoutAuthLayoutAuthLoginRoute,
}

const LayoutAuthLayoutRouteWithChildren =
  LayoutAuthLayoutRoute._addFileChildren(LayoutAuthLayoutRouteChildren)

interface LayoutMainLayoutAuthRouteChildren {
  LayoutMainLayoutAuthordersMyOrdersRoute: typeof LayoutMainLayoutAuthordersMyOrdersRoute
}

const LayoutMainLayoutAuthRouteChildren: LayoutMainLayoutAuthRouteChildren = {
  LayoutMainLayoutAuthordersMyOrdersRoute:
    LayoutMainLayoutAuthordersMyOrdersRoute,
}

const LayoutMainLayoutAuthRouteWithChildren =
  LayoutMainLayoutAuthRoute._addFileChildren(LayoutMainLayoutAuthRouteChildren)

interface LayoutMainLayoutRouteChildren {
  LayoutMainLayoutAuthRoute: typeof LayoutMainLayoutAuthRouteWithChildren
  LayoutMainLayoutIndexRoute: typeof LayoutMainLayoutIndexRoute
  LayoutMainLayoutuserProfileRoute: typeof LayoutMainLayoutuserProfileRoute
  LayoutMainLayoutEventEventIDRoute: typeof LayoutMainLayoutEventEventIDRoute
  LayoutMainLayoutordersOrderCodeRoute: typeof LayoutMainLayoutordersOrderCodeRoute
}

const LayoutMainLayoutRouteChildren: LayoutMainLayoutRouteChildren = {
  LayoutMainLayoutAuthRoute: LayoutMainLayoutAuthRouteWithChildren,
  LayoutMainLayoutIndexRoute: LayoutMainLayoutIndexRoute,
  LayoutMainLayoutuserProfileRoute: LayoutMainLayoutuserProfileRoute,
  LayoutMainLayoutEventEventIDRoute: LayoutMainLayoutEventEventIDRoute,
  LayoutMainLayoutordersOrderCodeRoute: LayoutMainLayoutordersOrderCodeRoute,
}

const LayoutMainLayoutRouteWithChildren =
  LayoutMainLayoutRoute._addFileChildren(LayoutMainLayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutMainLayoutAuthRouteWithChildren
  '/': typeof LayoutMainLayoutIndexRoute
  '/auth/login': typeof LayoutAuthLayoutAuthLoginRoute
  '/profile': typeof LayoutMainLayoutuserProfileRoute
  '/event/$eventID': typeof LayoutMainLayoutEventEventIDRoute
  '/order/$code': typeof LayoutMainLayoutordersOrderCodeRoute
  '/my-orders': typeof LayoutMainLayoutAuthordersMyOrdersRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutMainLayoutAuthRouteWithChildren
  '/': typeof LayoutMainLayoutIndexRoute
  '/auth/login': typeof LayoutAuthLayoutAuthLoginRoute
  '/profile': typeof LayoutMainLayoutuserProfileRoute
  '/event/$eventID': typeof LayoutMainLayoutEventEventIDRoute
  '/order/$code': typeof LayoutMainLayoutordersOrderCodeRoute
  '/my-orders': typeof LayoutMainLayoutAuthordersMyOrdersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout/_auth-layout': typeof LayoutAuthLayoutRouteWithChildren
  '/_layout/_main-layout': typeof LayoutMainLayoutRouteWithChildren
  '/_layout/_main-layout/_auth': typeof LayoutMainLayoutAuthRouteWithChildren
  '/_layout/_main-layout/': typeof LayoutMainLayoutIndexRoute
  '/_layout/_auth-layout/auth/login': typeof LayoutAuthLayoutAuthLoginRoute
  '/_layout/_main-layout/(user)/profile': typeof LayoutMainLayoutuserProfileRoute
  '/_layout/_main-layout/event/$eventID': typeof LayoutMainLayoutEventEventIDRoute
  '/_layout/_main-layout/(orders)/order/$code': typeof LayoutMainLayoutordersOrderCodeRoute
  '/_layout/_main-layout/_auth/(orders)/my-orders': typeof LayoutMainLayoutAuthordersMyOrdersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/auth/login'
    | '/profile'
    | '/event/$eventID'
    | '/order/$code'
    | '/my-orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/'
    | '/auth/login'
    | '/profile'
    | '/event/$eventID'
    | '/order/$code'
    | '/my-orders'
  id:
    | '__root__'
    | '/_layout/_auth-layout'
    | '/_layout/_main-layout'
    | '/_layout/_main-layout/_auth'
    | '/_layout/_main-layout/'
    | '/_layout/_auth-layout/auth/login'
    | '/_layout/_main-layout/(user)/profile'
    | '/_layout/_main-layout/event/$eventID'
    | '/_layout/_main-layout/(orders)/order/$code'
    | '/_layout/_main-layout/_auth/(orders)/my-orders'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutAuthLayoutRoute: typeof LayoutAuthLayoutRouteWithChildren
  LayoutMainLayoutRoute: typeof LayoutMainLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutAuthLayoutRoute: LayoutAuthLayoutRouteWithChildren,
  LayoutMainLayoutRoute: LayoutMainLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout/_auth-layout",
        "/_layout/_main-layout"
      ]
    },
    "/_layout/_auth-layout": {
      "filePath": "_layout/_auth-layout.tsx",
      "children": [
        "/_layout/_auth-layout/auth/login"
      ]
    },
    "/_layout/_main-layout": {
      "filePath": "_layout/_main-layout.tsx",
      "children": [
        "/_layout/_main-layout/_auth",
        "/_layout/_main-layout/",
        "/_layout/_main-layout/(user)/profile",
        "/_layout/_main-layout/event/$eventID",
        "/_layout/_main-layout/(orders)/order/$code"
      ]
    },
    "/_layout/_main-layout/_auth": {
      "filePath": "_layout/_main-layout/_auth.tsx",
      "parent": "/_layout/_main-layout",
      "children": [
        "/_layout/_main-layout/_auth/(orders)/my-orders"
      ]
    },
    "/_layout/_main-layout/": {
      "filePath": "_layout/_main-layout/index.tsx",
      "parent": "/_layout/_main-layout"
    },
    "/_layout/_auth-layout/auth/login": {
      "filePath": "_layout/_auth-layout/auth/login.tsx",
      "parent": "/_layout/_auth-layout"
    },
    "/_layout/_main-layout/(user)/profile": {
      "filePath": "_layout/_main-layout/(user)/profile.tsx",
      "parent": "/_layout/_main-layout"
    },
    "/_layout/_main-layout/event/$eventID": {
      "filePath": "_layout/_main-layout/event/$eventID.tsx",
      "parent": "/_layout/_main-layout"
    },
    "/_layout/_main-layout/(orders)/order/$code": {
      "filePath": "_layout/_main-layout/(orders)/order.$code.tsx",
      "parent": "/_layout/_main-layout"
    },
    "/_layout/_main-layout/_auth/(orders)/my-orders": {
      "filePath": "_layout/_main-layout/_auth/(orders)/my-orders.tsx",
      "parent": "/_layout/_main-layout/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
